version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install envsubst
          command: |
            apt-get update  && apt-get -y install gettext-base
      - run:
          name: Build the projects
          command: sh -e scripts/build.sh
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - run:
          name: Push to Docker Hub Registry
          command: sh -e scripts/push.sh
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            mv kubectl ~/
            chmod u+x ~/kubectl
      - run:
          name: Deploy Code
          command: sh -e scripts/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Credentials
