apiVersion: v1
kind: Service
metadata:
  name: servicio-productos-svc
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001
  selector:
    app: servicio-productos
