apiVersion: v1
kind: Service
metadata:
  name: servicio-config-server-svc
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 8888
  selector:
    app: servicio-config-server
