apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: {{.kops.clrName}}
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{.kops.stateStore}}
  etcdClusters:
  - etcdMembers:
  {{range $i, $a := .kops.masterZones}}
    - instanceGroup: master-{{.}}
      name: {{.}}
  {{end}}
    name: main
    version: 3.2.24
  - etcdMembers:
  {{range $i, $a := .kops.masterZones}}
    - instanceGroup: master-{{.}}
      name: {{.}}
  {{end}}
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.15.9
  masterPublicName: api.{{.kops.clrName}}
  networkCIDR: {{.kops.networkCIDR}}
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.1.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.1.64.0/19
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 10.1.96.0/19
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 10.1.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 10.1.4.0/22
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 10.1.8.0/22
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    bastion:
      bastionPublicName: bastion.{{.kops.clrName}}
    dns:
      type: Public
    masters: private
    nodes: private
---

{{range .kops.masterZones}}
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{$.kops.clrName}}
  name: master-{{.}}
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: {{$.kops.masterSize}}
  maxSize: {{$.kops.masterCount}}
  minSize: 1
  role: Master
  subnets:
  - {{.}}
---
{{end}}

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.kops.clrName}}
  name: bastions
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - utility-eu-west-1a
  - utility-eu-west-1b
  - utility-eu-west-1c
---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.kops.clrName}}
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
  kubernetesVersion: v1.15.9
  machineType: {{.kops.nodeSize}}
  maxSize: {{.kops.nodeCount}}
  minSize: 1
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c


