apiVersion: v1
kind: Service
metadata:
  name: servicio-zuul-server-svc
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
  selector:
    app: servicio-zuul-server
